// autogenerated from ../deps/nanomsg/src/core/symbol.c - manual edits inadvisable!
var nano = require('../');
var nn = nano._bindings;

exports.symbols = [
{
                'value': nn.NN_NS_NAMESPACE,
                'name':  "NN_NS_NAMESPACE",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_VERSION,
                'name':  "NN_NS_VERSION",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_DOMAIN,
                'name':  "NN_NS_DOMAIN",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_TRANSPORT,
                'name':  "NN_NS_TRANSPORT",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_PROTOCOL,
                'name':  "NN_NS_PROTOCOL",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_OPTION_LEVEL,
                'name':  "NN_NS_OPTION_LEVEL",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_SOCKET_OPTION,
                'name':  "NN_NS_SOCKET_OPTION",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_TRANSPORT_OPTION,
                'name':  "NN_NS_TRANSPORT_OPTION",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_OPTION_TYPE,
                'name':  "NN_NS_OPTION_TYPE",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_OPTION_UNIT,
                'name':  "NN_NS_OPTION_UNIT",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_FLAG,
                'name':  "NN_NS_FLAG",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_ERROR,
                'name':  "NN_NS_ERROR",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_LIMIT,
                'name':  "NN_NS_LIMIT",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_EVENT,
                'name':  "NN_NS_EVENT",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_NS_STATISTIC,
                'name':  "NN_NS_STATISTIC",
                'ns':    nn.NN_NS_NAMESPACE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_TYPE_NONE,
                'name':  "NN_TYPE_NONE",
                'ns':    nn.NN_NS_OPTION_TYPE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_TYPE_INT,
                'name':  "NN_TYPE_INT",
                'ns':    nn.NN_NS_OPTION_TYPE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_TYPE_STR,
                'name':  "NN_TYPE_STR",
                'ns':    nn.NN_NS_OPTION_TYPE,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_NONE,
                'name':  "NN_UNIT_NONE",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_BYTES,
                'name':  "NN_UNIT_BYTES",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_MILLISECONDS,
                'name':  "NN_UNIT_MILLISECONDS",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_PRIORITY,
                'name':  "NN_UNIT_PRIORITY",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_BOOLEAN,
                'name':  "NN_UNIT_BOOLEAN",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_COUNTER,
                'name':  "NN_UNIT_COUNTER",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_UNIT_MESSAGES,
                'name':  "NN_UNIT_MESSAGES",
                'ns':    nn.NN_NS_OPTION_UNIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_VERSION_CURRENT,
                'name':  "NN_VERSION_CURRENT",
                'ns':    nn.NN_NS_VERSION,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_VERSION_REVISION,
                'name':  "NN_VERSION_REVISION",
                'ns':    nn.NN_NS_VERSION,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_VERSION_AGE,
                'name':  "NN_VERSION_AGE",
                'ns':    nn.NN_NS_VERSION,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.AF_SP,
                'name':  "AF_SP",
                'ns':    nn.NN_NS_DOMAIN,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.AF_SP_RAW,
                'name':  "AF_SP_RAW",
                'ns':    nn.NN_NS_DOMAIN,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_INPROC,
                'name':  "NN_INPROC",
                'ns':    nn.NN_NS_TRANSPORT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_IPC,
                'name':  "NN_IPC",
                'ns':    nn.NN_NS_TRANSPORT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_TCP,
                'name':  "NN_TCP",
                'ns':    nn.NN_NS_TRANSPORT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_WS,
                'name':  "NN_WS",
                'ns':    nn.NN_NS_TRANSPORT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_PAIR,
                'name':  "NN_PAIR",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_PUB,
                'name':  "NN_PUB",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_SUB,
                'name':  "NN_SUB",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_REP,
                'name':  "NN_REP",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_REQ,
                'name':  "NN_REQ",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_PUSH,
                'name':  "NN_PUSH",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_PULL,
                'name':  "NN_PULL",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_SURVEYOR,
                'name':  "NN_SURVEYOR",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_RESPONDENT,
                'name':  "NN_RESPONDENT",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_BUS,
                'name':  "NN_BUS",
                'ns':    nn.NN_NS_PROTOCOL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_SOCKADDR_MAX,
                'name':  "NN_SOCKADDR_MAX",
                'ns':    nn.NN_NS_LIMIT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_SOL_SOCKET,
                'name':  "NN_SOL_SOCKET",
                'ns':    nn.NN_NS_OPTION_LEVEL,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_LINGER,
                'name':  "NN_LINGER",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_SNDBUF,
                'name':  "NN_SNDBUF",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BYTES
},
{
                'value': nn.NN_RCVBUF,
                'name':  "NN_RCVBUF",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BYTES
},
{
                'value': nn.NN_RCVMAXSIZE,
                'name':  "NN_RCVMAXSIZE",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BYTES
},
{
                'value': nn.NN_SNDTIMEO,
                'name':  "NN_SNDTIMEO",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_RCVTIMEO,
                'name':  "NN_RCVTIMEO",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_RECONNECT_IVL,
                'name':  "NN_RECONNECT_IVL",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_RECONNECT_IVL_MAX,
                'name':  "NN_RECONNECT_IVL_MAX",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_SNDPRIO,
                'name':  "NN_SNDPRIO",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_PRIORITY
},
{
                'value': nn.NN_RCVPRIO,
                'name':  "NN_RCVPRIO",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_PRIORITY
},
{
                'value': nn.NN_SNDFD,
                'name':  "NN_SNDFD",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_RCVFD,
                'name':  "NN_RCVFD",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_DOMAIN,
                'name':  "NN_DOMAIN",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_PROTOCOL,
                'name':  "NN_PROTOCOL",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_IPV4ONLY,
                'name':  "NN_IPV4ONLY",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BOOLEAN
},
{
                'value': nn.NN_SOCKET_NAME,
                'name':  "NN_SOCKET_NAME",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_STR,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_MAXTTL,
                'name':  "NN_MAXTTL",
                'ns':    nn.NN_NS_SOCKET_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_SUB_SUBSCRIBE,
                'name':  "NN_SUB_SUBSCRIBE",
                'ns':    nn.NN_NS_TRANSPORT_OPTION,
                'type':  nn.NN_TYPE_STR,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_SUB_UNSUBSCRIBE,
                'name':  "NN_SUB_UNSUBSCRIBE",
                'ns':    nn.NN_NS_TRANSPORT_OPTION,
                'type':  nn.NN_TYPE_STR,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_REQ_RESEND_IVL,
                'name':  "NN_REQ_RESEND_IVL",
                'ns':    nn.NN_NS_TRANSPORT_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_SURVEYOR_DEADLINE,
                'name':  "NN_SURVEYOR_DEADLINE",
                'ns':    nn.NN_NS_TRANSPORT_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MILLISECONDS
},
{
                'value': nn.NN_TCP_NODELAY,
                'name':  "NN_TCP_NODELAY",
                'ns':    nn.NN_NS_TRANSPORT_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BOOLEAN
},
{
                'value': nn.NN_WS_MSG_TYPE,
                'name':  "NN_WS_MSG_TYPE",
                'ns':    nn.NN_NS_TRANSPORT_OPTION,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_DONTWAIT,
                'name':  "NN_DONTWAIT",
                'ns':    nn.NN_NS_FLAG,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_WS_MSG_TYPE_TEXT,
                'name':  "NN_WS_MSG_TYPE_TEXT",
                'ns':    nn.NN_NS_FLAG,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_WS_MSG_TYPE_BINARY,
                'name':  "NN_WS_MSG_TYPE_BINARY",
                'ns':    nn.NN_NS_FLAG,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_POLLIN,
                'name':  "NN_POLLIN",
                'ns':    nn.NN_NS_EVENT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_POLLOUT,
                'name':  "NN_POLLOUT",
                'ns':    nn.NN_NS_EVENT,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EADDRINUSE,
                'name':  "EADDRINUSE",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EADDRNOTAVAIL,
                'name':  "EADDRNOTAVAIL",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EAFNOSUPPORT,
                'name':  "EAFNOSUPPORT",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EAGAIN,
                'name':  "EAGAIN",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EBADF,
                'name':  "EBADF",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ECONNREFUSED,
                'name':  "ECONNREFUSED",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EFAULT,
                'name':  "EFAULT",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EFSM,
                'name':  "EFSM",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EINPROGRESS,
                'name':  "EINPROGRESS",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EINTR,
                'name':  "EINTR",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EINVAL,
                'name':  "EINVAL",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EMFILE,
                'name':  "EMFILE",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENAMETOOLONG,
                'name':  "ENAMETOOLONG",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENETDOWN,
                'name':  "ENETDOWN",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENOBUFS,
                'name':  "ENOBUFS",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENODEV,
                'name':  "ENODEV",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENOMEM,
                'name':  "ENOMEM",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENOPROTOOPT,
                'name':  "ENOPROTOOPT",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENOTSOCK,
                'name':  "ENOTSOCK",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENOTSUP,
                'name':  "ENOTSUP",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EPROTO,
                'name':  "EPROTO",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EPROTONOSUPPORT,
                'name':  "EPROTONOSUPPORT",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ETERM,
                'name':  "ETERM",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ETIMEDOUT,
                'name':  "ETIMEDOUT",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EACCES,
                'name':  "EACCES",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ECONNABORTED,
                'name':  "ECONNABORTED",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ECONNRESET,
                'name':  "ECONNRESET",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EHOSTUNREACH,
                'name':  "EHOSTUNREACH",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.EMSGSIZE,
                'name':  "EMSGSIZE",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENETRESET,
                'name':  "ENETRESET",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENETUNREACH,
                'name':  "ENETUNREACH",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.ENOTCONN,
                'name':  "ENOTCONN",
                'ns':    nn.NN_NS_ERROR,
                'type':  nn.NN_TYPE_NONE,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_STAT_ESTABLISHED_CONNECTIONS,
                'name':  "NN_STAT_ESTABLISHED_CONNECTIONS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_ACCEPTED_CONNECTIONS,
                'name':  "NN_STAT_ACCEPTED_CONNECTIONS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_DROPPED_CONNECTIONS,
                'name':  "NN_STAT_DROPPED_CONNECTIONS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_BROKEN_CONNECTIONS,
                'name':  "NN_STAT_BROKEN_CONNECTIONS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_CONNECT_ERRORS,
                'name':  "NN_STAT_CONNECT_ERRORS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_BIND_ERRORS,
                'name':  "NN_STAT_BIND_ERRORS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_ACCEPT_ERRORS,
                'name':  "NN_STAT_ACCEPT_ERRORS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_COUNTER
},
{
                'value': nn.NN_STAT_MESSAGES_SENT,
                'name':  "NN_STAT_MESSAGES_SENT",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MESSAGES
},
{
                'value': nn.NN_STAT_MESSAGES_RECEIVED,
                'name':  "NN_STAT_MESSAGES_RECEIVED",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_MESSAGES
},
{
                'value': nn.NN_STAT_BYTES_SENT,
                'name':  "NN_STAT_BYTES_SENT",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BYTES
},
{
                'value': nn.NN_STAT_BYTES_RECEIVED,
                'name':  "NN_STAT_BYTES_RECEIVED",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_BYTES
},
{
                'value': nn.NN_STAT_CURRENT_CONNECTIONS,
                'name':  "NN_STAT_CURRENT_CONNECTIONS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_STAT_INPROGRESS_CONNECTIONS,
                'name':  "NN_STAT_INPROGRESS_CONNECTIONS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
},
{
                'value': nn.NN_STAT_CURRENT_SND_PRIORITY,
                'name':  "NN_STAT_CURRENT_SND_PRIORITY",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_PRIORITY
},
{
                'value': nn.NN_STAT_CURRENT_EP_ERRORS,
                'name':  "NN_STAT_CURRENT_EP_ERRORS",
                'ns':    nn.NN_NS_STATISTIC,
                'type':  nn.NN_TYPE_INT,
                'unit':  nn.NN_UNIT_NONE
}
];
